#!/usr/bin/env python3
"""Render conservative release gates from identity and recorded validation facts."""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from lucy_diagnose.identity import IDENTITY


def evaluate(identity, facts):
    gates = []
    def add(name, passed, detail):
        gates.append({'gate': name, 'status': 'PASS' if passed is True else 'BLOCKED', 'detail': detail})
    for name, field in [('Application name','display_name'),('Publisher','publisher'),('Tagline','tagline'),
                        ('Application license selected','license')]:
        add(name, bool(identity.get(field)), identity.get(field) or 'Decision remains unresolved')
    for name, field, ready in [('Application ID','application_id', identity.get('application_id_finalized') is True),
                               ('Developer ID','developer_id', bool(identity.get('developer_id'))),
                               ('Target repository namespace','repository_namespace', bool(identity.get('repository_url')))]:
        add(name, bool(identity.get(field)) and ready, identity.get(field) or 'Approved target not set')
    for name, field in [('Remote repository created','remote_repository_created'),
                        ('Homepage reachable','homepage_reachable'),('Support/issues reachable','support_reachable'),
                        ('Security reporting configured','security_reporting_configured')]:
        passed = identity.get(field) is True and (field == 'remote_repository_created' or identity.get('remote_repository_created') is True)
        add(name, passed, 'Remote configuration verified' if passed else 'BLOCKED: remote repository/configuration not yet created or verified')
    for name, field in [('CI green on GitHub','ci_remote_passed'),('Automated tests green','tests_passed'),
                        ('Flatpak builds and launches','flatpak_validated'),('AppImage builds and launches','appimage_validated'),
                        ('Checksums verified','checksums_verified'),('Builds reproduced','reproduced'),
                        ('Manual save flow tested','manual_save_flow'),('Privacy review complete for current tree','privacy_review'),
                        ('Git history/author privacy approved for publication','history_approved'),
                        ('Screen-sharing status documented','capture_documented'),('Audio status documented','audio_documented'),
                        ('SMART status documented','smart_documented'),('Strict AppStream validation','appstream_clean'),
                        ('README complete','readme_complete'),('CHANGELOG complete','changelog_complete'),
                        ('Clean final Git tree','git_clean'),('Book checkpoint written','book_checkpoint'),
                        ('Bundled-runtime advisory/source-obligation review','distribution_review'),
                        ('Explicit public release action approved','release_approved')]:
        add(name, facts.get(field) is True, facts.get(field + '_detail', 'See NAMESPACE-VALIDATION.md for current evidence; earlier validation reports preserve prior scope'))
    gates.append({'gate':'Windows/macOS package release', 'status':'NOT APPLICABLE', 'detail':'Diagnostics remain UNSUPPORTED placeholders; Linux-only release candidate'})
    return gates


def render(gates):
    return ('# Release checklist\n\nGenerated by `scripts/release-checklist.py` from central identity and the\n'
            'recorded validation facts. PASS means only the stated gate, not release approval.\n\n'
            + ('**PUBLIC RELEASE BLOCKER: Application license not selected.**\n\n'
               if any(g['gate'] == 'Application license selected' and g['status'] == 'BLOCKED' for g in gates) else '')
            +
            '| Gate | Status | Evidence / limit |\n|---|---|---|\n' + ''.join(
                f'| {g["gate"]} | **{g["status"]}** | {g["detail"]} |\n' for g in gates))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--facts', type=Path, default=ROOT / 'docs/validation/rc1-release-facts.json')
    args = parser.parse_args()
    facts = json.loads(args.facts.read_text()) if args.facts.exists() else {}
    print(render(evaluate(IDENTITY, facts)), end='')
